version: '1'

services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build: ./python-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
